// Generated by CodiumAI

describe('displayinfoConclusion', function () {
    it('Deve retornar "Normal" com valores entre 0 e 3', function () {
        const expectValue = 'Normal';

        expect(displayinfoConclusion(0)).toEqual(expectValue);
        expect(displayinfoConclusion(2)).toEqual(expectValue);
        expect(displayinfoConclusion(4)).not.toEqual(expectValue);
    });

    it('Deve retornar "Normal. Pontuação entre 4 e 7. Re-teste opcional" com valores superiores a 7', function () {
        const expectValue = 'Normal. Pontuação entre 4 e 7. Re-teste opcional';

        expect(displayinfoConclusion(4)).toEqual(expectValue);
        expect(displayinfoConclusion(5)).toEqual(expectValue);
        expect(displayinfoConclusion(7)).toEqual(expectValue);
        expect(displayinfoConclusion(8)).not.toEqual(expectValue);
    });

    it('Deve retornar string vazia se score for null', function () {
        expect(displayinfoConclusion(null)).toEqual('');
    });

    it('Deve retornar string vazia se score for isNaN', function () {
        expect(displayinfoConclusion('isNaN')).toEqual('');
    });

    it('Deve retornar string vazia se score for undefined', function () {
        expect(displayinfoConclusion(undefined)).toEqual('');
        expect(displayinfoConclusion()).toEqual('');
    });
});
