// Generated by CodiumAI

describe('Display Info Result Function', function () {
    it('Deve retornar "Normal" com valores entre 0 e 7', function () {
        expect(displayInfoResult(0)).toEqual('Normal');
        expect(displayInfoResult(4)).toEqual('Normal');
        expect(displayInfoResult(7)).toEqual('Normal');
        expect(displayInfoResult(8)).not.toEqual('Normal');
    });

    it('Deve retornar "Indicado para frenectomia" com valores superiores a 7', function () {
        expect(displayInfoResult(7)).not.toEqual('Indicado para frenectomia');
        expect(displayInfoResult(8)).toEqual('Indicado para frenectomia');
        expect(displayInfoResult(10)).toEqual('Indicado para frenectomia');
    });
    
    it('Deve retornar string vazia se score null', function () {
        expect(displayInfoResult(null)).toEqual('');
    });

    it('Deve retornar string vazia se score isNaN', function () {
        expect(displayInfoResult('isNaN')).toEqual('');
    });

    it('Deve retornar string vazia se score undefined', function () {
        expect(displayInfoResult(undefined)).toEqual('');
        expect(displayInfoResult()).toEqual('');
    });
});
